sudo: false

language: go

git:
  depth: 1

install: 
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
  email: deploy@travis-ci.org
  name: deployment-bot