sudo: false

language: go

git:
  depth: 1

install: go get -v github.com/spf13/hugo

script:
  - hugo

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  keep-history: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
  email: deploy@travis-ci.org
  name: deployment-bot