language: go

git:
  depth: 1

install: 
  - pushd /tmp/
  - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*hugo_extended.*_Linux-64bit\.tar\.gz" | cut -d ":" -f 2,3 | tr -d \" | wget -qi -
  - tarball="$(find . -name "*Linux-64bit.tar.gz")"
  - tar -xzf $tarball
  - chmod +x hugo
  - popd

script:
  - /tmp/hugo

deploy:
  provider: pages
  keep_history: true
  # token is set in travis-ci.org dashboard
  token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
  email: deploy@travis-ci.org
  name: deployment-bot