baseURL = "https://blog.heysh.xyz/"
languageCode = "zh-cn"
title = "林中阴影"
theme = "tokiwa"
copyright = "&copy;贺叶霜，<a href=\"https://creativecommons.org/licenses/by-sa/4.0/deed.zh\">CC BY-SA</a>"
hasCJKLanguage = true
author = "HeYSH"
# Shown in the side menu
canonifyurls = false
paginate = 10
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = 'manni'
# pygmentsUseClasses=true

googleAnalytics = "UA-40522664-1"
disqusShortname = "heysh"
# pygmentsOptions = "linenos=table,noclasses=true"

[markup.goldmark.renderer]
unsafe= true
[permalinks]
post = "/:year/:month/:day/:filename/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[indexes]
  tag = "tags"
  topic = "categories"

[params]
  math = true
  env = "production"
  description = """
  那里的颜色正是常磐色。
  """
  favicon = "img/favicon.png"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "归档"
    identifier = "post"
    url = "/post/"
    weight = 1
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "关于"
    identifier = "about"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "内心戏"
    identifier = "sentences"
    url = "/sentences/"
    weight = 4

  [[menu.main]]
    name = "云乞讨"
    identifier = "begging"
    weight = 4
    url = "/wallet/"
  [[menu.main]]
    name = "芽"
    identifier = "home"
    url = "https://heysh.xyz/"
    weight = 5

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "https://twitter.com/heyeshuang"
  # googleplus = "贺叶霜HeYSH"

  # Techie
  github = "https://github.com/heyeshuang"
