baseURL = "https://blog.heysh.xyz/"
languageCode = "zh-cn"
title = "贺叶霜的树：III"
theme = "blackburn"
copyright = "&copy;<a href=\"https://creativecommons.org/licenses/by-sa/4.0/deed.zh\">CC BY-SA</a>"
hasCJKLanguage = true
author = "HeYSH"
# Shown in the side menu
canonifyurls = false
paginate = 10
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = 'manni'
# pygmentsUseClasses=true
# pygmentsOptions = "linenos=table,noclasses=true"

[permalinks]
post = "/:year/:month/:day/:filename/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[indexes]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  subtitle = "第三根树苗"
  brand = "Rei III"
  googleAnalytics = "UA-40522664-1"
  disqus = "HeYSH"
  valine_id = "t7xAhuTsStq91vofdFBaMyoG-gzGzoHsz"
  valine_key = "NdrP2qik4G319EwHthKo9lSC"
  # CSS name for highlight.js
  # highlightjs = "atom-one-light"
  dateFormat = "2006-01-02 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/typo.css","css/custom.css"]
  # custom_js = ["js/my.js"]

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Theatre"
    pre = "<i class='fa fa-video-camera fa-fw'></i>"
    weight = 3
    identifier = "sentences"
    url = "/sentences/"

  [[menu.main]]
    name = "Begging"
    pre = "<i class='fa fa-money fa-fw'></i>"
    weight = 3
    identifier = "begging"
    url = "/wallet/"
  [[menu.main]]
    name = "Bud"
    pre = "<i class='fa fa-pagelines fa-fw'></i>"
    weight = 3
    identifier = "home"
    url = "https://heysh.xyz/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "heyeshuang"
  googleplus = "贺叶霜HeYSH"

  # Techie
  github = "heyeshuang"
